### ISSUE TITLE
关于小程序 sdk.config.json 内不再自动填入腾讯云密钥的通知

### ISSUE THREAD

**Issue by jas0ncn** [tencentyun/wafer2-quickstart#13]
出于安全考虑，即日起，我们不再帮助用户无感知的申请腾讯云云 API 密钥，受此影响，腾讯云微信小程序解决方案 Wafer2 提供的 `sdk.config.json` 中的 `qcloudSecretId` 和 `qcloudSecretKey` 字段将为空，这会导致登录失败，并返回错误提示：`ERR_REQUEST_PARAM `。

你可以通过以下两种方式修复该问题：

**1. 关闭腾讯云代理登录，使用微信小程序 AppID 和 AppSecret 登录：**

修改 `server/config.js` 中的 `useQcloudLogin` 为 `false`，并填写上 `appId` 和 `appSecret` 字段（分别为**微信小程序**的 AppID 和 AppSecret），重新部署代码即可。

**2. 手动填写腾讯云云 API 密钥：**

登录[腾讯云云 API 密钥控制台](https://console.cloud.tencent.com/capi)申请云 API 密钥，并在 `server/config.js` 的 `CONF` 中添加如下三个字段：

```javascript
    qcloudAppId: '你的腾讯云 AppID',
    qcloudSecretId: '你的腾讯云 SecretId',
    qcloudSecretKey: '你的腾讯云 SecretKey',
```

重新部署代码即可生效。

由于上传接口也会使用到腾讯云云 API 密钥，如遇到上传接口报错，也请参考如上 2 的方法排查。

对您使用带来的不便，敬请谅解。

**Comment by jas0ncn** [comment]
PHP 环境同理操作

**1. 关闭腾讯云代理登录，使用微信小程序 AppID 和 AppSecret 登录：**

修改 `server/config.php` 中的 `useQcloudLogin` 为 `false`，并填写上 `appId` 和 `appSecret` 字段（分别为**微信小程序**的 AppID 和 AppSecret），重新部署代码即可。

**2. 手动填写腾讯云云 API 密钥：**

登录[腾讯云云 API 密钥控制台](https://console.cloud.tencent.com/capi)申请云 API 密钥，并在 `server/config.php` 的 `$config` 中添加如下三个字段：

```javascript
    'qcloudAppId' => 1200000000, // 腾讯云 AppID，必须是数字
    'qcloudSecretId' => '你的腾讯云 SecretId',
    'qcloudSecretKey' => '你的腾讯云 SecretKey',
```

**Comment by littlekillua** [comment]
按照php版第一条修改之后，登录没有问题，腾讯云的上传提示 `QcloudSecretId`不能为空，请确保 SDK 配置已正确初始化

**Comment by Shennng** [comment]
使用第二种方法申请云API密钥，问题解决。
使用第一种方法，问题未解决。

**Comment by NicoTic** [comment]
使用第一种方法，问题解决。

**Comment by crofsun** [comment]
采用第二种方法解决了，第一种还是报的参数错误。

**Comment by ChrisAtLondon** [comment]
第一种方法修改完以后记得要重新部署server端代码。

**Comment by xrlu0929** [comment]
我手残。。combine了两种 好了。。。

**Comment by wenqistr** [comment]
为什么上传图片不行

**Comment by wenqistr** [comment]
第一种不能上传图片   第二种还要改  region: 'cn-south', 很奇怪

**Comment by luwy007** [comment]
请问使用新版开发工具，在点击上传代码之后，开发环境的服务就会重新部署吗

**Comment by tangyongjing** [comment]
> 请问使用新版开发工具，在点击上传代码之后，开发环境的服务就会重新部署吗

同问

**Comment by epoll486** [comment]
![image](https://user-images.githubusercontent.com/20532016/50734121-b6da2780-11d4-11e9-840d-8623d5666257.png)

**Comment by epoll486** [comment]
> > 请问使用新版开发工具，在点击上传代码之后，开发环境的服务就会重新部署吗
> 
> 同问

![image](https://user-images.githubusercontent.com/20532016/50734129-e0934e80-11d4-11e9-839b-ffcfebeffea3.png)

**Comment by limingbaiaixiezuo** [comment]
什么情况？？？
`Error: 响应错误，{"code":-1,"error":"ERR_GET_SESSION_KEY\n{\"code\":5100,\"message\":\"(-1)服务内部错误，请稍后重试或联系客服人员解决。\",\"codeDesc\":\"ResourceOpFailed\"}"}
    at success (http://127.0.0.1:45531/appservice/vendor/wafer2-client-sdk/lib/login.js:85:38)
    at Function.function.e.(anonymous function) (http://127.0.0.1:45531/appservice/__dev__/WAService.js:1:546456)
    at http://127.0.0.1:45531/appservice/__dev__/WAService.js:1:101855
    at be (http://127.0.0.1:45531/appservice/__dev__/WAService.js:1:259651)
    at pt.<anonymous> (http://127.0.0.1:45531/appservice/__dev__/WAService.js:1:390782)
    at pt.emit (http://127.0.0.1:45531/appservice/__dev__/WAService.js:1:294578)
    at vi (http://127.0.0.1:45531/appservice/__dev__/WAService.js:1:391290)
    at http://127.0.0.1:45531/appservice/__dev__/WAService.js:1:391927
    at http://127.0.0.1:45531/appservice/__dev__/WAService.js:1:254754
    at e (http://127.0.0.1:45531/appservice/appservice?t=1547805571602:1148:2640)`

**Comment by MKC-Mankii** [comment]
改了这么久，为什么不更新一下官方文档呢？
https://cloud.tencent.com/document/product/619/11447

**Comment by WREQI** [comment]
@limingbaiaixiezuo 遇到同样问题解决没？

**Comment by jgslzw** [comment]
用的第一种方法可以解决，改完之后，重置开发环境，上传测试代码，重新部署之后就可以了。

**Comment by fanzhanxiang** [comment]
用第一种方法解决了、感谢

**Comment by fanxeon** [comment]
登录只要用户有EMOJI就会响应错误怎么办,数据库是MB4编码的了
`Error: 响应错误，{"code":-1,"error":"ERR_WHEN_INSERT_TO_DB\nError: insert into `cSessionInfo` (`create_time`, `last_visit_time`, `open_id`, `session_key`, `skey`, `user_info`, `uuid`) values ('2019-07-12 17:19:00', '2019-07-12 17:19:00', 'ojjJr5b2fUGGUTpBYecJ3zmyzUZw', 'z8bWRid6/Z4bGrg9nC768A==', '05eda7b5118f491584a2b22115ed1a4ac3ec1b66', '{\\\"openId\\\":\\\"ojjJr5b2fUGGUTpBYecJ3zmyzUZw\\\",\\\"nickName\\\":\\\"断肠人 诗上科技🐾\\\",\\\"gender\\\":0,\\\"language\\\":\\\"zh_CN\\\",\\\"city\\\":\\\"\\\",\\\"province\\\":\\\"\\\",\\\"country\\\":\\\"\\\",\\\"avatarUrl\\\":\\\"https://wx.qlogo.cn/mmopen/vi_32/a9DnvgQvJYlNkG9K7u0hcGJZbqKjiaj4VLIjBeia6NTu4WhR8TopfF6PwekMicrVbe7YfMdDctxA7s4n450TEudBg/132\\\",\\\"watermark\\\":{\\\"timestamp\\\":1562923139,\\\"appid\\\":\\\"wxffabcc62a4272690\\\"}}', 'f4398045-0792-4b18-96c9-58e69f7f0a02') - ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect string value: '\\xF0\\x9F\\x90\\xBE\",...' for column 'user_info' at row 1"}`

**Comment by hjy030212** [comment]
还是不行
![Uploading QQ截图20201201204751.png…]()

**Comment by hjy94wo777** [comment]
还是不行啊！
index.js:39 Error: 响应错误，"<br />\n<b>Parse error</b>:  syntax error, unexpected ':', expecting ']' in <b>/data/release/php-weapp-demo/config.php</b> on line <b>7</b><br />\n"
    at success (login.js:84)
    at Function.i.<computed> (VM406 WAService.js:2)
    at C (VM406 WAService.js:2)
    at VM406 WAService.js:2
    at u (VM406 WAService.js:2)
    at Function.<anonymous> (VM406 WAService.js:2)
    at C (VM406 WAService.js:2)
    at VM406 WAService.js:2
    at VM406 WAService.js:2
    at Set.forEach (<anonymous>)
