### ISSUE TITLE
发起登录请求，返回Error: 响应错误，{"code":-1,"error":"ERR_REQUEST_PARAM"}

### ISSUE THREAD

**Issue by OrangeSnow** [tencentyun/wafer2-quickstart#14]
请求源码确定没问题，用的是官方实例，看其他issue，貌似存在刚开通腾讯云，会出现类似的问题，而申请比较久的账号，就不会返回error，这是腾讯云的一个bug吗

**Comment by jas0ncn** [comment]
https://github.com/tencentyun/wafer2-quickstart/issues/13
