### ISSUE TITLE
"code":-1,"error":"ERR_SKEY_INVALID"

### ISSUE THREAD

**Issue by yujianhui1993** [tencentyun/wafer2-quickstart#15]
小程序登录失败 提示 "code":-1,"error":"ERR_SKEY_INVALID"
请问这个错误如果解决。我看了 数据库中 有我登录的信息，但是没有返回数据给我。这个问题已经很久了，希望能帮我看看。

**Comment by jas0ncn** [comment]
SKEY过期了吧？应该重新调用登录接口的

**Comment by yujianhui1993** [comment]
我调用的就是登录接口，登录接口都报这个错，请问怎么处理。

**Comment by yujianhui1993** [comment]
@jas0ncn nodejs模块 有封装了登录方法，调用这个登录方法时候报错，怎么处理，我也知道skey过期，问题是怎么解决。

**Comment by jas0ncn** [comment]
查看一下这个 https://github.com/tencentyun/wafer2-client-sdk#%E7%99%BB%E5%BD%95
如果登录态过期，应该调用 `qcloud.loginWithCode`

**Comment by yujianhui1993** [comment]
@jas0ncn 已经解决了，在你们wafer2 升级之前，我修改过login方法，多加入一个  validationMiddleware 验证登入状态，升级之后在登入的时候验证就出问题了，我把它改回去，就正常了。

**Comment by jas0ncn** [comment]
OK~
