### ISSUE TITLE
上传正式代码的时候，提示错误

### ISSUE THREAD

**Issue by dingo826** [tencentyun/wafer2-quickstart#2]

**Comment by jas0ncn** [comment]
请先登录 https://console.qcloud.com/lav2/production 开通生产环境哈

**Comment by Tangbots** [comment]
![2017-10-16 10 41 05](https://user-images.githubusercontent.com/30828777/31592998-94db2d12-b1f1-11e7-9e2d-0f1c06adb5b4.png)
第一次上传测试代码到腾讯云

**Comment by jas0ncn** [comment]
您好，已经修复兼容问题。下载代码，创建项目即可。
