### ISSUE TITLE
登录失败如何解决？？

### ISSUE THREAD

**Issue by yuxianwen** [tencentyun/wafer2-quickstart#3]
登录失败

message
:
"{"code":-1,"error":"ERR_WHEN_INSERT_TO_DB\nError: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: YES)"}"
type
:
"ERR_LOGIN_MISSING_SESSION"

一步一步来的，

**Comment by jas0ncn** [comment]
开发环境吗？有没有修改 server/config.js 里面的 mysql 的 pass 字段呢？修改完了要上传的。

**Comment by yuxianwen** [comment]
不知道什么原因，我自己又从新弄了，估计是config 文件没有正常上传上去吧，导致数据库链接失败。已经正常了，谢谢
