### ISSUE TITLE
npm i 出错

### ISSUE THREAD

**Issue by AlbertHuyb** [tencentyun/wafer2-quickstart#5]
npm i
[  ................] / fetchMetadata: sill fetchPackageMetaData error for wafer-node-sdk@^1.0.7 No mat[  ................] / fetchMetadata: sill fetchPackageMetaData error for wafer-node-sdk@^1.0.7 No matnpm ERR! code ETARGET
npm ERR! notarget No matching version found for wafer-node-sdk@^1.0.7
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'koa-weapp-demo'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-11-01T11_08_18_609Z-debug.log

求助，多谢~！

**Comment by jas0ncn** [comment]
检查你的 npm 源有没有问题。不要使用 cnpm
